services:
  - type: web
    name: ethicalmetrics
    env: go
    plan: free
    autoDeploy: true
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: REDIS_ADDR
        value: redis-15775.c239.us-east-1-2.ec2.redns.redis-cloud.com:15775
      - key: REDIS_USER
        value: default
      - key: REDIS_PASS
        value: GcGuQQUaaOeFuB2CcpFSTxhepS9PIFR4

