services:
  - type: web
    name: ethicalmetrics
    env: go
    plan: free
    autoDeploy: true
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: DB_KEY
        value: secure_db_key
