name: Go Report Card Checks
on: [push, pull_request]
jobs:
  report-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go install github.com/goreportcard/goreportcard-cli@latest
      - run: goreportcard-cli -v
