name: GitHub Issue Vote Ranking

on:
  reaction:
    types: [created]

jobs:
  vote-ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: livrasand/gh-issue-vote-ranking@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ranking_issue_number: "1" 
          ignore_label: "ignore-issue"  
          language: "en"  
