name: GitHub Issue Vote Ranking

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  vote-ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: livrasand/gh-issue-vote-ranking@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ranking_issue_number: "1" 
          ignore_label: "ignore-issue"  
          language: "en"  
